In [1]:
import pandas as pd
import seaborn as sns

In [2]:
house_data=pd.read_csv("house_predection.csv")
house_data

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,NaN
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,NaN
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,NaN
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,NaN
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,NaN

In [15]:
train_data = house_data[house_data["SalePrice"].notna()]

X=train_data.drop(columns=["SalePrice"])
y=train_data["SalePrice"]


X.head()

,Id,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,MSZoning_FV,MSZoning_RH,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
0,0,60,8450,5,2003,2003,0.0,856.0,False,False,...,False,False,False,False,False,False,False,True,False,False
1,1,20,9600,8,1976,1976,0.0,1262.0,False,False,...,False,False,False,True,False,False,False,False,False,False
2,2,60,11250,5,2001,2002,0.0,920.0,False,False,...,False,False,False,False,False,False,False,True,False,False
3,3,70,9550,5,1915,1970,0.0,756.0,False,False,...,False,False,False,False,False,False,False,False,True,False
4,4,60,14260,5,2000,2000,0.0,1145.0,False,False,...,False,False,False,False,False,False,False,True,False,False

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)
X = pd.get_dummies(X, drop_first=True)
X_train.head()

,Id,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,MSZoning_FV,MSZoning_RH,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
254,254,20,8400,6,1957,1957,0.0,1314.0,False,False,...,False,False,False,True,False,False,False,False,False,False
1066,1066,60,7837,7,1993,1994,0.0,799.0,False,False,...,False,False,False,False,False,False,False,True,False,False
638,638,30,8777,7,1910,1950,0.0,796.0,False,False,...,False,False,False,True,False,False,False,False,False,False
799,799,50,7200,7,1937,1950,0.0,731.0,False,False,...,False,False,False,False,False,False,False,False,True,False
380,380,50,5000,6,1924,1950,0.0,1026.0,False,False,...,False,False,False,False,False,False,False,False,False,False

In [18]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [21]:
y_pred=model.predict(X_test)
y_pred

array([168733.00189055, 243223.76121104, 114785.4122782 , 157880.21908253,
       254517.60086045, 156703.57888498, 178379.56166675, 127064.11121206,
       133197.4188594 , 149331.19082235, 131000.75218361, 122815.2050272 ,
        79738.39227967, 239339.94776738, 218129.44955194, 177551.1420249 ,
       218101.29975088, 178803.12616051, 135322.80805372, 233339.70771398,
       163212.59495861, 219590.49747873, 202612.80166674, 154541.464804  ,
       224316.14395911, 167384.05651946, 228422.20457254, 110932.01963278,
       215243.13926239, 205067.00490291, 115672.66061879, 231708.53736396,
       224244.0047091 , 129036.96376607, 251253.52486046, 140922.92968161,
       170428.17798619, 217706.51759572, 254810.7443039 ,  78172.67334397,
       119177.72918109, 218351.79277335, 125276.92523566, 291207.78191568,
       141515.57653548, 104779.22150903, 127608.97846475, 131336.69938212,
       320741.92793949, 146047.68650293, 111720.04894557, 193398.07005701,
       123511.08279431, 262847.33569266, 152093.76336412, 260183.03113034,
       181201.01289117, 171125.25343238, 197830.2532489 ,  85436.40562154,
        62742.76287073, 208960.04840226, 244926.36857892, 246582.38537191,
       261850.2612704 , 190599.79464049, 119326.83099988, 272090.40112036,
       163262.01007901, 179951.23024359,  55600.38813102, 116369.46742788,
       123679.80659675,  32960.87467544, 316397.94525019, 304014.31742053,
       254514.71840475, 252786.1096788 , 179295.14339927, 125410.27687606,
       114224.73884048,  76199.30928323, 116784.416016  ,  85277.92417049,
       161293.03398609, 156201.41255442, 245025.51993466, 303727.84472276,
       151852.90707808, 210900.08870448, 180521.47189814, 169118.15907697,
       142037.37792067, 214148.33524602, 185590.24094676, 224651.92437035,
       178805.32539811, 183633.77469433, 240246.16740906, 215058.48893026,
       183447.34538945, 219235.35368902, 249666.55210499, 156288.77911903,
       229463.54766291, 186976.69175907, 167106.08626426, 316119.61563604,
       180490.05975053, 175306.10453096,  37479.18432668, 147656.64083363,
       168679.69848465, 174618.15932643, 229770.65276746, 127337.66829428,
       143974.56272324, 135112.34503193,  55496.10434506, 370826.42505218,
       145166.32154496, 152637.538152  , 213462.41550496, 165283.6269403 ,
       191974.87080212, 132438.80756144, 221273.37263003,  99584.98038765,
       203028.14998701, 163654.78994618, 211982.5435485 , 271467.76189321,
       210048.54498741, 117317.12801665,  39581.3971683 , 273318.04842705,
       239713.50196605, 159771.97005575, 245877.18027693, 335506.02747037,
       261581.71964618, 172359.63078542, 169955.70415619, 138682.7382592 ,
       184697.07314936, 173575.5868457 , 212635.73384479, 231000.11232849,
       232718.21488989,  90994.1606288 ,  81290.14057685, 146179.0794353 ,
       254445.57998049, 130620.73209775, 100884.66986872, 123922.24649078,
       139307.32055875, 163778.91076585, 119417.72485464, 127187.62223239,
       219645.41126373, 144695.46797112, 253695.34883899, 167702.93582952,
       127028.0474551 , 224040.91679069, 220105.37522656, 298834.97686627,
       342535.80203668, 175232.42212825, 271694.65828206, 140582.53631963,
       132366.36694256, 114647.43888065, 255299.70578024,  85810.89335406,
       112156.27681358, 218016.54611745, 151684.44902525, 163142.23720323,
       289613.16938832,  62881.16154825, 202302.77318755, 137994.40087272,
       233273.42123563, 114439.66452097, 276818.03521604, 205070.12423039,
       207380.96583607, 112248.94931751, 118064.30214262, 122787.52235484,
       122215.95952991, 212415.55831623, 180194.31060323, 156774.43939922,
       197013.12894335, 119391.31085338, 181621.31942663, 102637.90327079,
       230074.94319608, 186016.09313189, 145667.06599094, 261733.01286425,
       221420.81881271, 184807.60264278, 228754.49084715, 146709.41975011,
       176112.57606856, 113311.2302242 , 177489.26715671, 117522.30975787,
       116102.93757133, 181201.76495899, 204988.38811379, 250067.53534474,
       198317.60311299, 180367.46422933, 185716.90280909,  54674.29948726,
       130230.17826068, 206000.83105197, 186581.31980165, 111815.1890097 ,
       238407.82003676, 195721.39069227,  62594.68001241, 134993.43575145,
       182423.51539461,  75107.16473499,  81542.61453607, 177730.7164022 ,
       132292.0387862 , 144952.43062798, 194331.20198962, 166140.17018248,
       216017.90529004, 222245.69602135, 216295.12664952, 122749.40750404,
       119259.75210634, 218390.50725231, 231067.11050662, 284135.7184043 ,
       170152.13339537, 162619.48062126, 184364.39187134, 174184.34318089,
       157812.03201424,  83070.52682207, 218923.55761336, 159866.451254  ,
       149941.68879457,  85810.98338458, 139011.11805031, 128983.91614307,
       149988.18859452, 130317.61106269, 192388.11218616, 236936.23968688,
       277692.12143169, 169431.95798164, 124829.27750408, 282921.09725584,
       283209.85139065, 242503.38531362, 167691.64951899, 150833.86491157,
       114543.422012  , 191993.0623582 , 290535.33723942, 173272.21298922,
       242480.90742517, 129146.64000624,  20294.15867405, 150625.53158706,
       175906.89071787, 254001.83963865, 238185.63867204, 137480.15933418,
       226327.01125382, 144975.66557532, 215696.1470387 , 139128.12642698,
       260498.76761161, 233383.33929306, 223996.87320377, 155704.4031736 ,
       245307.5010903 , 221367.11322083, 133564.15814646, 143246.01708565])

In [22]:
y_test

892     154500.0
1105    325000.0
413     115000.0
522     159000.0
1036    315500.0
          ...
479      89471.0
1361    260000.0
802     189000.0
651     108000.0
722     124500.0
Name: SalePrice, Length: 292, dtype: float64

In [25]:
#evaluation
from sklearn.metrics import r2_score
r2=r2_score(y_test, y_pred)
print(r2)
n=X_test.shape[0]
p=X_test.shape[1]
adjusted_r2=1-((1-r2)*(n-1)/(n-p-1))
print("adjusted r^2:",adjusted_r2)

0.6196387511449771
adjusted r^2: 0.5693185859268028