In [2]:
import pandas as pd
import seaborn as sns

In [3]:
insurance_data=pd.read_csv("insurance.csv")

In [4]:
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [5]:
X=insurance_data.drop(columns=["charges","region"])
y=insurance_data["charges"]
X["sex"]=X["sex"].map({"female":1,"male":0})
X["smoker"]=X["smoker"].map({"yes":1,"no":0})
X["age_smoker"]=X["age"]*X["smoker"]
X["bmi_smoker"]=X["bmi"]*X["smoker"]
X.head()

   age  sex     bmi  children  smoker  age_smoker  bmi_smoker
0   19    1  27.900         0       1          19        27.9
1   18    0  33.770         1       0           0         0.0
2   28    0  33.000         3       0           0         0.0
3   33    0  22.705         0       0           0         0.0
4   32    0  28.880         0       0           0         0.0

In [6]:
#tain test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [7]:
X_train.head()

      age  sex    bmi  children  smoker  age_smoker  bmi_smoker
560    46    1  19.95         2       0           0         0.0
1285   47    1  24.32         0       0           0         0.0
1142   52    1  24.86         0       0           0         0.0
969    39    1  34.32         5       0           0         0.0
486    54    1  21.47         3       0           0         0.0

In [8]:
#train model
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [9]:
#predict values
y_pred=model.predict(X_test)
y_pred

array([10586.93796866,  7333.82725483, 33112.12796247, 10810.96321326,
       28060.12164781,  6876.36321462,  2800.22322323, 14253.41872519,
        5120.3829701 , 11625.10286298, 21310.84514261,  9074.05090258,
        5955.00513313, 51973.28429449, 52193.0919527 , 46756.37735164,
       11790.52835522, 43401.07296481, 10409.9580634 , 27534.42349972,
        6204.84749492,  9617.21646063,  2360.18919617,  3739.1003023 ,
       12391.58848601, 12088.14519394, 13686.25099182,  6366.007644  ,
       11125.01663956,  2095.08458968, 10238.2348701 , 12869.24181602,
        3433.34407627,  7063.67062128,  4661.44068919,  9275.90865148,
        3824.51623886,  9637.51349725, 26335.81123438, 37866.62794949,
        5177.25220562,  3621.80458848, 13105.78612637, 12830.98397083,
        7016.16971379, 13313.54619145,  4352.20827881,  5787.27735357,
       41788.53588932,  6513.43838694, 14485.21693542,  2553.21236091,
        8949.15474091,  2060.17202231, 12120.45160384, 11452.86202352,
        5208.51470565, 36276.36476976, 13143.17238911, 11830.25788032,
       14446.08703427,  6800.32280247, 14843.66198006,  9796.75451399,
       11546.76222028,  5660.37919009, 21298.12551162, 12393.72139435,
        4842.10916192,  3227.84985514,  7876.86941418, 10911.73741326,
       10516.73468419,  8563.58055083,  9462.7145097 ,  7332.95770147,
        5876.40907548, 12552.70312833,  6186.636467  , 11056.3264559 ,
        2648.51087736, 31792.74174787,  7210.18583057, 37550.23542804,
       59722.18399979, 36154.08687654,  6656.11441218, 11843.21672798,
       10109.16282321, 12745.25960473, 15167.62831465, 27380.77985713,
       27943.35490406,  6420.00487851, 37879.11763675,  9088.05071166,
       27578.135492  ,  3154.23966069, 20723.20357052,  7943.63092857,
        6207.54469359,  2855.7442052 ,  8228.4900482 , 13529.44314123,
       13340.97606823,  2603.90732174,  9863.45175923, 20875.16930919,
        2019.69431345, 24762.08754854,  2383.66713687,  4805.17785944,
       13601.86537003, 33017.61790557, 11222.2281734 ,  3110.46468337,
       13121.0882364 , 28191.84952221,  8533.10020299,  3849.95317722,
        7301.04962489,  9105.44177884, 12541.66886408,  3721.8856484 ,
        6107.02885699,  9604.12717996,  9687.42586006, 10705.36910707,
       13424.27677741,  3511.64985886,  6272.97405215,  7994.24596838,
        8051.41206743,  9771.28974983,  8146.5321415 , 13397.02331392,
        6082.13180513, 31343.82723724, 45553.22870289, 31672.14175857,
        7306.56675702, 11310.35287463,  4243.74714915, 12534.23418286,
        3896.73061623, 27658.27183827,  6944.04026266,  6011.6085251 ,
       12726.3008389 ,  7031.38236587, 46262.78594899,  3900.33676006,
        2190.73545917, 34494.01125454,  8416.03252416,  6340.01911874,
       13677.3405725 , 10684.2799355 , 30319.76084178, 35360.75024626,
       14061.73224798,  3293.13312882, 15076.06684856,  3360.34757439,
        4826.03399079,  9394.1982367 , 48760.39455655, 37543.39715962,
       34326.33547124,  4444.98055882, 11139.79451496,  8608.74681352,
        7723.62831562,  5940.31218397,  3628.62354803, 26382.66060098,
       21850.5480908 , 14275.80972418, 12122.67354015, 12794.06892813,
       34104.62379167,  3741.16954939, 10090.46539691,  7304.96261501,
        6314.53258776,  4208.61469084,  5446.84160039,  5736.59101031,
       10822.97369627, 11798.60864067,  4864.29433858,  2595.20475384,
        3594.53705636, 38622.03563052, 13735.77455823, 11311.96154835,
        3282.39414484, 12984.7488305 ,  2570.42248311, 10975.20574506,
        4637.65137051, 30115.21485096,  6301.28958   ,  3262.57536257,
       21824.11658847, 20143.17055735, 10473.65081786,  4972.48553884,
       10067.43991386,  4827.19632181, 13584.21140775, 13265.8486871 ,
       11048.86597798, 22768.04663766,  8762.33823604,  5738.59098303,
        6994.90209985, 14754.66069115, 13594.33920177,  7572.2411049 ,
        3440.73527982,  9010.58665664,  8626.10596905, 44399.07007716,
        3163.58986191, 30097.41531479,  2783.5712764 ,  2361.84134756,
       11232.79574932, 12709.65342377,  2941.96292336, 11172.39823422,
        6376.43775261, 28372.21376961, 11437.72022906, 10301.58842078,
        5133.87261318,  8437.76932905, 48041.1427763 ,  3178.02444767,
       13540.47037118, 36913.65533913,  4481.37136689,  5169.34335592,
        2314.75503317,  4205.87810037,  6138.81103226,  6251.54659617,
       14008.92047652,  2247.84290219,  3124.67484648,  9316.98643012,
        5194.38196096, 12785.80817122,  3346.00197305,  4926.58627075,
       13123.74037415,  4695.4837032 , 10176.93794676,  7418.20879075,
        9768.10726251, 13827.27033399, 26109.00913202, 44411.27800453,
       13091.60787492,  7798.39222353, 60657.85481964, 11777.6544338 ])

In [10]:
 y_test

764      9095.06825
887      5272.17580
890     29330.98315
1293     9301.89355
259     33750.29180
           ...
109     47055.53210
575     12222.89830
535      6067.12675
543     63770.42801
846      9872.70100
Name: charges, Length: 268, dtype: float64

In [11]:
#evaluate
from sklearn.metrics import r2_score
r_square=r2_score(y_test, y_pred)
print(r_square)

0.8631145226569426

In [15]:
#underfit&overfit
y_train_pred=model.predict(X_train)
r2_train=r2_score(y_train,y_train_pred)
print(r2_train)
print(r_square)

0.832648622477355
0.8631145226569426